### PR TITLE
Add support for SF Symbols 5.4 and 6

### LINKED ISSUE #136: Support for SF Symbols 6
Title says it all, iOS and other OSes added new SF Symbols and changed a few ones... It would be awesome to make the new SF Symbols available via SFSafeSymbol

### PR DESCRIPTION
**Pull request by RodBrown1988**
Resolves #136

### CODE REVIEW

**Comment by RodBrown1988** [comment]
Interesting, Bitrise is saying Xcode Test for iOS (15.5) failed, but the test associated here passed.

**Comment by RodBrown1988** [comment]
@StevenSorial Not sure who to ping about getting a review on this, but would be great to get SF Symbols 6 in if possible?

**Comment by StevenSorial** [comment]
yes It's me, sorry for not responding as I didn't have the time recently. I will try to take a look in the coming days.

**Comment by StevenSorial** [comment]
@RodBrown1988 There are many new localizations that Apple has added but our parser is not updated.
you can see how they are causing generated code to include extra symbols instead of adding localization to an old one.
Screenshot 2024-11-05 at 01 13 01
Screenshot 2024-11-05 at 01 13 15

**Comment by RodBrown1988** [comment]
@StevenSorial ah right, I didn't realise! I'll get this updated.

**Comment by RodBrown1988** [comment]
@StevenSorial I've added the new localisations and re-run. Thanks!

**Comment by StevenSorial** [comment]
Thanks. The new code uses new `SymbolWith..Localizations` classes that need to be written manually. The project doesn't compile now

**Comment by RodBrown1988** [comment]
Ouch. Ok, I’ll take a look. Should have run it. 🤦‍♂️

**Comment by RodBrown1988** [comment]
@StevenSorial looks like it’s building correctly now.

**Comment by StevenSorial** [comment]
Thanks for the PR. Merged. 🎉

**Comment by RodBrown1988** [comment]
Thanks @StevenSorial , that's great. Do we have any word on a new release version with this, or are we awaiting updates for APIs now available in Xcode 16? Interested in helping out here 👍

**Comment by eschos24** [comment]
Would also love to have access to this.

**Comment by StevenSorial** [comment]
@RodBrown1988 @eschos24 Released a new version with 6.2 symbols

**Pull request merged**
