### PR TITLE
Added button initializers

### PR DESCRIPTION
**Pull request by Rspoon3**
Added multiple initializers for SwiftUI Button.

### CODE REVIEW

**Comment by Rspoon3** [comment]
Hi @StevenSorial. I see that some tests are failing. When I try to run them locally, I get "Command AppIntentsSSUTraining failed with a nonzero exit code". How can I run them on my machine to ensure everything is working correctly?

**Comment by StevenSorial** [comment]
try to rebase your branch on the latest `stable`.

**Comment by Rspoon3** [comment]
I just rebased on the latest stable branch and I’m still getting the same error.

**Comment by StevenSorial** [comment]
> I get "Command AppIntentsSSUTraining failed with a nonzero exit code"

This is the error I'm also seeing. seems to be a familiar issue.  https://forums.developer.apple.com/forums/thread/732535

**Comment by Rspoon3** [comment]
@StevenSorial any suggestions on getting this moving?

**Comment by StevenSorial** [comment]
@Rspoon3  I'm open to merging the PR if the test build issue is solved.
I've found that this piece of code is the problem:
```swift
    @available(iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0, *)
    struct OrderSoupIntent: AppIntent {
        static var title = LocalizedStringResource("Order Soup")
        static var description = IntentDescription("Orders a soup from your favorite restaurant.")
        
        init() { }
        
        func perform() async throws -> some IntentResult {
            return .result()
        }
    }
```

**Comment by Rspoon3** [comment]
@StevenSorial I removed the problematic code. Seems like this is now good to merge in.

**Comment by StevenSorial** [comment]
@Rspoon3 can you please look into #63 and see if we have the same issue with these new initializers?
if you take a look at `/Applications/Xcode-15.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/SwiftUI.framework/Modules/SwiftUI.swiftmodule/arm64-apple-ios.swiftinterface` you will see that some of these initialzers should be marked with `@_disfavoredOverload`

**Comment by Rspoon3** [comment]
@StevenSorial Great callout, I had no idea about this. I just pushed the change.

**Comment by Rspoon3** [comment]
@StevenSorial Is there anything else that needs to be done here? It would be great it we can get this merged in.

**Pull request merged**
